### ISSUE TITLE
Lexeme cannot be created with forms in query parameters

### ISSUE THREAD

**Issue by strepon** [lucaswerkmeister/tool-lexeme-forms#16]
It seems that creating lexemes with forms as query parameters stopped to work during the last week.

For instance, go to [this URL containing forms](https://lexeme-forms.toolforge.org/template/czech-noun-neuter/?form_representation=z%C5%99en%C3%AD&form_representation=z%C5%99en%C3%AD&form_representation=z%C5%99en%C3%AD&form_representation=z%C5%99en%C3%AD&form_representation=z%C5%99en%C3%AD&form_representation=z%C5%99en%C3%AD&form_representation=z%C5%99en%C3%ADm&form_representation=z%C5%99en%C3%AD&form_representation=z%C5%99en%C3%AD&form_representation=z%C5%99en%C3%ADm&form_representation=z%C5%99en%C3%AD&form_representation=z%C5%99en%C3%AD&form_representation=z%C5%99en%C3%ADch&form_representation=z%C5%99en%C3%ADmi) and press the Create button - no lexeme is created.

A workaround: go to the "Advanced" mode and press Create, then the new lexeme is created as expected.

**Comment by lucaswerkmeister** [comment]
It seems to work now, which means it probably broke when I tried to simplify the URL handling in cb0855af488cdf8dc686e0c7ad4ea234761e5ca9, and was then fixed by d237952e44caa7b6471e12d510dcc11480a6f6da and later f4e7ba98a746a8092c2310045f8f30d932c7023e. Can you try again, please? (With a different word than <q lang=cs>zření</q> since I just created that one ☺)

**Comment by strepon** [comment]
Yes, confirming that it works now. Thank you!
