### ISSUE TITLE
Invisible field on the form French adjective

### ISSUE THREAD

**Issue by envlh** [lucaswerkmeister/tool-lexeme-forms#74]
Hello,

Steps to reproduce:
1. Go to https://lexeme-forms.toolforge.org/template/french-adjective/edit/L11202
2. Drag and drop the available form on the field "masculin singulier" (top left)
3. Start typing on the field "féminin singulier" (top right)

Issue: what you write or paste in this field is invisible.

Notes:
* Other fields are not affected.
* While the content is invisible, it really exists, and when you submit the form, it is properly taken into account.
* If you use the Pick feature from the Firefox inspector (F12), the content of the field becomes visible permanently.

The bug was found with Firefox 88.0 on Windows. @belett was able to reproduce it with Firefox 90.0 on Windows. I was unable to reproduce it on Chromium 85.0.4161.0 on Windows.

Cheers,
Envel

**Comment by lucaswerkmeister** [comment]
WTF… can confirm…

I’ll take a look, but surely this has to be a bug in Firefox?

**Comment by lucaswerkmeister** [comment]
If I find the `<input>` in the dev tools without using the pick feature (so that the bug doesn’t vanish), I can make the behavior disappear and reappear by disabling and reenabling certain CSS rules. For instance, disabling the `line-height: inherit` alone is usually enough to make the form field behave normally; reenabling it often makes the input invisible again.

(For testing, I actually just focus the input and see if a cursor is visible or not, which is faster than typing something. When the bug is there, the cursor is also invisible.)

**Comment by lucaswerkmeister** [comment]
Should be fixed for now; I’ll see if I can reproduce this issue and report it to Firefox.

**Comment by lucaswerkmeister** [comment]
Reported at https://bugzilla.mozilla.org/show_bug.cgi?id=1721262.

**Comment by envlh** [comment]
Thank you Lucas for the workaround (I can confirm that the form now properly works with Firefox 88) and for reporting the issue to the Firefox project.
